In [1]:
import pandas as pd
import pyranges1 as pr

## Import mm39 annotations

In [ ]:
ann = pr.read_gtf("data/gencode.vM39.basic.annotation.gtf")

## Import mm39 rmsk

In [ ]:
rmsk_cols = [
    "bin", "swScore", "milliDiv", "milliDel",
    "milliIns", "Chromosome", "Start", "End", "genoLeft",
    "strand", "repName", "repClass", "repFamily",
    "repStart", "repEnd", "repLeft", "id"
]

df = pd.read_csv(
    "data/rmsk.txt",
    sep="\t",
    header=None,
    names=rmsk_cols
)

rmsk = pr.PyRanges(df)

## Filter retrotransposons and protein coding genes

In [4]:
retrotransposons = rmsk[rmsk['repClass'].isin(['LINE', 'SINE', 'LTR'])]

In [5]:
genes = ann[(ann['Feature'] == 'gene') & (ann['gene_type'] == 'protein_coding')]

## Nearest Retrotransposon to each gene

In [6]:
genes.nearest_ranges(retrotransposons)

index    |    Chromosome    Source      Feature    Start     End       ...
int64    |    str           category    str        int64     int64     ...
-------  ---  ------------  ----------  ---------  --------  --------  -----
6        |    chr1          HAVANA      gene       3276123   3742031   ...
6        |    chr1          HAVANA      gene       3276123   3742031   ...
6        |    chr1          HAVANA      gene       3276123   3742031   ...
6        |    chr1          HAVANA      gene       3276123   3742031   ...
...      |    ...           ...         ...        ...       ...       ...
4942892  |    chrY          HAVANA      gene       90412516  90444532  ...
4942892  |    chrY          HAVANA      gene       90412516  90444532  ...
4942892  |    chrY          HAVANA      gene       90412516  90444532  ...
4942892  |    chrY          HAVANA      gene       90412516  90444532  ...
PyRanges with 1472596 rows, 43 columns, and 1 index columns (with 1450839 index duplicates). (38 columns not shown: "Score", "Strand", "Frame", ...).
Contains 21 chromosomes and 2 strands.

## k nearest distances between a retrotransposon and a selected gene
Returns all of the retrotransposons at each distance. So there will always be k distinct distances, but there could be more than one retrotransposon at each distance.

In [7]:
gene = genes.sample(1)
k_nearest = gene.nearest_ranges(retrotransposons, k=5)
print(k_nearest.value_counts('Distance'))
k_nearest

Distance
0       30
1093     1
1628     1
1695     1
2130     1
Name: count, dtype: int64

index    |    Chromosome    Source      Feature    Start     End       ...
int64    |    str           category    str        int64     int64     ...
-------  ---  ------------  ----------  ---------  --------  --------  -----
2517166  |    chr9          HAVANA      gene       58730131  58770458  ...
2517166  |    chr9          HAVANA      gene       58730131  58770458  ...
2517166  |    chr9          HAVANA      gene       58730131  58770458  ...
2517166  |    chr9          HAVANA      gene       58730131  58770458  ...
...      |    ...           ...         ...        ...       ...       ...
2517166  |    chr9          HAVANA      gene       58730131  58770458  ...
2517166  |    chr9          HAVANA      gene       58730131  58770458  ...
2517166  |    chr9          HAVANA      gene       58730131  58770458  ...
2517166  |    chr9          HAVANA      gene       58730131  58770458  ...
PyRanges with 34 rows, 43 columns, and 1 index columns (with 33 index duplicates). (38 columns not shown: "Score", "Strand", "Frame", ...).
Contains 1 chromosomes and 1 strands.